#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Simon Keimer (DC0SK)
"""Regenerate the human-readable traceability matrix from the machine-readable
requirements register plus the `// VERIFIES: <ID>` citations in the code.

  docs/project/requirements.toml  +  code citations
        -->  docs/project/traceability-matrix-generated.md   (DO NOT hand-edit)

The GAP/DANGLING invariants are ENFORCED by apps/nec-cli/tests/traceability.rs
(which runs in the CI test gate); this script only renders the current state.

Usage:  python3 scripts/gen-traceability-matrix.py [--check]
  --check  exit non-zero if the generated file is out of date (for CI), do not write.
"""
from __future__ import annotations

import datetime
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTER = ROOT / "docs" / "project" / "requirements.toml"
OUT = ROOT / "docs" / "project" / "traceability-matrix-generated.md"
VERIFIES = re.compile(r"VERIFIES:\s*([A-Z][A-Z0-9-]*)")


def collect_citations() -> dict[str, list[str]]:
    cites: dict[str, list[str]] = {}
    for top in ("crates", "apps"):
        for rs in sorted((ROOT / top).rglob("*.rs")):
            if rs.name == "traceability.rs" or "target" in rs.parts:
                continue
            for i, line in enumerate(rs.read_text().splitlines(), 1):
                m = VERIFIES.search(line)
                if m:
                    rel = rs.relative_to(ROOT)
                    cites.setdefault(m.group(1), []).append(f"{rel}:{i}")
    return cites


def render(reqs: list[dict], cites: dict[str, list[str]]) -> str:
    today = datetime.date.today().isoformat()
    lines = [
        "---",
        "project: fnec-rust",
        "doc: docs/project/traceability-matrix-generated.md",
        "status: living",
        f"last_updated: {today}",
        "---",
        "",
        "# Traceability matrix (generated — do not hand-edit)",
        "",
        "Generated by `scripts/gen-traceability-matrix.py` from",
        "`docs/project/requirements.toml` and the `// VERIFIES: <ID>` citations in the",
        "code. The GAP/DANGLING invariants are enforced by",
        "`apps/nec-cli/tests/traceability.rs` in the CI test gate. Edit the register or",
        "the citations, then regenerate — never edit this file by hand.",
        "",
        "| ID | Title | Status | Criticality | Verification | Verified by |",
        "|:---|:------|:-------|:------------|:-------------|:------------|",
    ]
    for r in reqs:
        rid = r["id"]
        verif = r["verification"]
        if verif == "test":
            sites = cites.get(rid, [])
            by = "<br>".join(f"`{s}`" for s in sites) if sites else "**— GAP —**"
        else:
            by = f"review — {r.get('rationale', '').strip()}"
        lines.append(
            f"| {rid} | {r['title']} | {r['status']} | {r['criticality']} | {verif} | {by} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    check = "--check" in sys.argv[1:]
    reqs = tomllib.loads(REGISTER.read_text())["requirement"]
    content = render(reqs, collect_citations())
    if check:
        current = OUT.read_text() if OUT.exists() else ""
        # ignore the last_updated line when comparing (it is intentionally volatile)
        def strip_date(t: str) -> str:
            return re.sub(r"last_updated: .*", "last_updated: <date>", t)

        if strip_date(current) != strip_date(content):
            print(f"{OUT} is out of date; run: python3 scripts/gen-traceability-matrix.py", file=sys.stderr)
            return 1
        print("traceability matrix is up to date")
        return 0
    OUT.write_text(content)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
